name: Deploy to GitHub Pages

on:
  push:
    branches:
      - rough
  # allows manual triggering from GitHub UI:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Cancel running deployments if a new one is issued.
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-node@v2
      - run: npm install

      - name: Install SASS globally (to pre-compile CSS in following task)
        run: npm install -g sass

      - name: Package all required files into 'dist' folder e.g. compile CSS
        run: npm run github-actions-build

      - name: Use the Upload Artifact GitHub Action to upload 'dist' folder
        uses: actions/upload-pages-artifact@v1
        with: 
          name: github-pages
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1